name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Criar diretório dist
        run: mkdir -p dist

      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: GildeanLS
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake-artifact
          path: dist

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
